# Generated by Django 3.0.2 on 2020-03-23 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApacheLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.GenericIPAddressField()),
                ('time', models.DateTimeField()),
                ('request_method', models.PositiveSmallIntegerField(choices=[(0, 'GET'), (1, 'POST'), (2, 'DELETE'), (3, 'OPTIONS'), (4, 'PATCH'), (5, 'PUT'), (6, 'HEAD'), (7, 'Undefined')])),
                ('request_path', models.TextField()),
                ('protocol', models.CharField(max_length=50)),
                ('status', models.PositiveIntegerField()),
                ('size', models.PositiveIntegerField()),
                ('agent', models.TextField()),
                ('referrer', models.TextField()),
            ],
            options={
                'verbose_name': 'Apache лог',
                'verbose_name_plural': 'Apache логи',
            },
        ),
    ]
